"""Support different referral systems

Revision ID: 069abf9bbcdf
Revises: b09526fdabc8
Create Date: 2026-02-17 15:21:49.988284

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "069abf9bbcdf"
down_revision: Union[str, Sequence[str], None] = "b09526fdabc8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referral_bonuses",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("referral_id", sa.BigInteger(), nullable=True),
        sa.Column("referrer_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.TIMESTAMP(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "bonus_type",
            sa.Enum(
                "REGISTRATION",
                "TRAFFIC",
                "PURCHASE",
                name="referralbonustype",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("days_added", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["referral_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referral_id"),
    )
    op.drop_table("referral_payments")
    op.add_column(
        "users",
        sa.Column(
            "referral_type",
            sa.Enum(
                "STANDARD",
                "ONLY_REGISTRATIONS",
                "ALL_PAYMENTS_PERCENTAGE",
                name="referraltype",
                native_enum=False,
            ),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "referral_type")
    op.create_table(
        "referral_payments",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("referral_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("referrer_id", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column(
            "paid_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("days_added", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["referral_id"],
            ["users.id"],
            name=op.f("referral_payments_referral_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["users.id"],
            name=op.f("referral_payments_referrer_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("referral_payments_pkey")),
        sa.UniqueConstraint(
            "referral_id",
            name=op.f("referral_payments_referral_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("referral_bonuses")
    # ### end Alembic commands ###
