"""Remove default referral_type column value

Revision ID: 86e9edbf0f0e
Revises: b8855b49629e
Create Date: 2026-02-18 01:17:25.668821

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "86e9edbf0f0e"
down_revision: Union[str, Sequence[str], None] = "b8855b49629e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
