"""Referral program migration #1

Revision ID: b09526fdabc8
Revises: d6932a3afa1b
Create Date: 2026-02-17 03:49:31.023831

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b09526fdabc8"
down_revision: Union[str, Sequence[str], None] = "d6932a3afa1b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "referral_payments",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("referral_id", sa.BigInteger(), nullable=True),
        sa.Column("referrer_id", sa.BigInteger(), nullable=True),
        sa.Column(
            "paid_at", sa.TIMESTAMP(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("days_added", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["referral_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["referrer_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("referral_id"),
    )
    op.add_column("users", sa.Column("referred_by_id", sa.BigInteger(), nullable=True))
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.create_foreign_key(None, "users", "users", ["referred_by_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_column("users", "referred_by_id")
    op.drop_table("referral_payments")
    # ### end Alembic commands ###
