"""Fix referral_bonuses unique constraint

Revision ID: b8855b49629e
Revises: 069abf9bbcdf
Create Date: 2026-02-18 00:19:53.854556

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "b8855b49629e"
down_revision: Union[str, Sequence[str], None] = "069abf9bbcdf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("referral_bonuses_referral_id_key"), "referral_bonuses", type_="unique"
    )
    op.create_unique_constraint(
        "uix_referral_bonus_type", "referral_bonuses", ["referral_id", "bonus_type"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uix_referral_bonus_type", "referral_bonuses", type_="unique")
    op.create_unique_constraint(
        op.f("referral_bonuses_referral_id_key"),
        "referral_bonuses",
        ["referral_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
