"""Unique and non-nullable username

Revision ID: d6932a3afa1b
Revises: 6b46a3337ae1
Create Date: 2026-02-05 01:56:51.627878

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d6932a3afa1b"
down_revision: Union[str, Sequence[str], None] = "6b46a3337ae1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=256), nullable=False
    )
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.alter_column(
        "users", "username", existing_type=sa.VARCHAR(length=256), nullable=True
    )
    # ### end Alembic commands ###
